### ISSUE TITLE
Must we add resources/backoffice/envribbon_bof.jar to .gitignore ?

### ISSUE THREAD

**Issue by haruka-7** [sap-commerce-tools/environment-ribbon#2]
After each ant clean all, the jar below is generated : 

`resources/backoffice/envribbon_bof.jar`

Am I missing something or must I add this jar to our .gitignore ?

**Comment by mpern** [comment]
The implicit assumption is that you've a gitignore covering all known Commerce build artifacts already in place

https://github.com/SAP-samples/cloud-commerce-sample-setup/blob/main/.gitignore
